/**
 * reportExport.ts
 * Shared PDF / CSV / Print utilities for HRM report generation.
 * Uses jsPDF + jsPDF-AutoTable for PDF; plain string serialisation for CSV.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportColumn {
  header: string;
  key: string;
  /** optional value formatter */
  format?: (v: unknown) => string;
}

export interface ReportMeta {
  companyName: string;
  reportTitle: string;
  /** Optional subtitle / filter description shown under the title */
  subtitle?: string;
}

// ─── helpers ────────────────────────────────────────────────────────────────

function resolveCell(row: Record<string, unknown>, col: ReportColumn): string {
  const raw = row[col.key];
  if (col.format) return col.format(raw);
  if (raw === null || raw === undefined) return '—';
  return String(raw);
}

// ─── PDF ────────────────────────────────────────────────────────────────────

export function generatePDF(
  meta: ReportMeta,
  columns: ReportColumn[],
  rows: Record<string, unknown>[],
): void {
  // Choose orientation based on column count
  const orientation = columns.length > 7 ? 'landscape' : 'portrait';
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 14;

  const generatedDate = new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });

  // ── Draw header on first page ──
  const drawHeader = () => {
    // Company name
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 20, 20);
    doc.text(meta.companyName, marginX, 15);

    // Divider line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(marginX, 18, pageWidth - marginX, 18);

    // Report title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40, 40, 40);
    doc.text(meta.reportTitle, marginX, 25);

    // Subtitle / filters
    let y = 31;
    if (meta.subtitle) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(meta.subtitle, marginX, y);
      y += 6;
    }

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(130, 130, 130);
    doc.text(`Generated: ${generatedDate}`, marginX, y);
    doc.text(`Total Records: ${rows.length}`, pageWidth - marginX, y, { align: 'right' });

    return y + 4; // startY for table
  };

  const startY = drawHeader();

  // ── Table ──
  autoTable(doc, {
    startY,
    head: [columns.map(c => c.header)],
    body: rows.map(row => columns.map(col => resolveCell(row, col))),
    styles: {
      fontSize: columns.length > 8 ? 7 : 8,
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [28, 28, 28],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: columns.length > 8 ? 7 : 8,
    },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    margin: { left: marginX, right: marginX },
    // Draw page number footer on every page
    didDrawPage: (data) => {
      const pageNum = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
      const currentPage = data.pageNumber;
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'normal');
      doc.text('Generated by HRM System', marginX, pageHeight - 6);
      doc.text(`Page ${currentPage} of ${pageNum}`, pageWidth - marginX, pageHeight - 6, { align: 'right' });
      // Thin footer line
      doc.setDrawColor(220, 220, 220);
      doc.line(marginX, pageHeight - 9, pageWidth - marginX, pageHeight - 9);
    },
  });

  // Filename: sanitised title + date
  const safeName = meta.reportTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`${safeName}_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── CSV ────────────────────────────────────────────────────────────────────

function escapeCSV(val: string): string {
  if (/[",\n]/.test(val)) return `"${val.replace(/"/g, '""')}"`;
  return val;
}

export function generateCSV(
  meta: ReportMeta,
  columns: ReportColumn[],
  rows: Record<string, unknown>[],
): void {
  const header = columns.map(c => escapeCSV(c.header)).join(',');
  const body = rows.map(row =>
    columns.map(col => escapeCSV(resolveCell(row, col))).join(',')
  );
  const csv = [header, ...body].join('\n');

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeName = meta.reportTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  a.download = `${safeName}_${new Date().toISOString().split('T')[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Print ───────────────────────────────────────────────────────────────────

/**
 * Opens a fresh window containing only the formatted report and prints it.
 * Using a dedicated window avoids all issues with the SPA's DOM/CSS
 * interfering with print output. No popup-blocker risk because the call is
 * made synchronously from a user-click event handler.
 */
export function printReport(
  meta: ReportMeta,
  columns: ReportColumn[],
  rows: Record<string, unknown>[],
): void {
  const generatedDate = new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });

  const thead = `<tr>${columns.map(c => `<th>${escapeHTML(c.header)}</th>`).join('')}</tr>`;
  const tbody = rows
    .map((row, i) =>
      `<tr class="${i % 2 === 0 ? '' : 'alt'}">${
        columns.map(col => `<td>${escapeHTML(resolveCell(row, col))}</td>`).join('')
      }</tr>`,
    )
    .join('');

  const subtitleLine = meta.subtitle
    ? `<p class="subtitle">${escapeHTML(meta.subtitle)}</p>`
    : '';

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHTML(meta.reportTitle)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, Helvetica, sans-serif; color: #111; padding: 20px; font-size: 11pt; }

    .header { border-bottom: 2px solid #222; padding-bottom: 10px; margin-bottom: 16px; }
    .company  { font-size: 18pt; font-weight: 700; color: #111; }
    .report-title { font-size: 13pt; font-weight: 600; color: #333; margin-top: 4px; }
    .subtitle { font-size: 9pt; color: #666; margin-top: 3px; }
    .meta-row { display: flex; justify-content: space-between; font-size: 8pt; color: #888; margin-top: 6px; }

    table { width: 100%; border-collapse: collapse; margin-top: 4px; page-break-inside: auto; }
    thead tr { background: #222; color: #fff; }
    th { padding: 7px 8px; font-size: 9pt; text-align: left; font-weight: 600; }
    td { padding: 6px 8px; font-size: 9pt; border-bottom: 1px solid #e0e0e0; }
    tr.alt td { background: #f7f7f7; }
    tr { page-break-inside: avoid; }

    .footer { margin-top: 18px; border-top: 1px solid #ddd; padding-top: 6px;
              display: flex; justify-content: space-between; font-size: 8pt; color: #aaa; }

    @media print {
      body { padding: 12px; }
      @page { margin: 15mm; size: A4; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">${escapeHTML(meta.companyName)}</div>
    <div class="report-title">${escapeHTML(meta.reportTitle)}</div>
    ${subtitleLine}
    <div class="meta-row">
      <span>Generated: ${generatedDate}</span>
      <span>Total Records: ${rows.length}</span>
    </div>
  </div>

  <table>
    <thead>${thead}</thead>
    <tbody>${tbody}</tbody>
  </table>

  <div class="footer">
    <span>Generated by HRM System</span>
    <span>${escapeHTML(meta.reportTitle)} — ${new Date().toLocaleDateString()}</span>
  </div>

  <script>
    window.onload = function () {
      window.focus();
      window.print();
      setTimeout(function () { window.close(); }, 1000);
    };
  <\/script>
</body>
</html>`;

  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) {
    // Fallback: should not happen on a synchronous click handler, but guard anyway
    console.error('printReport: window.open blocked');
    return;
  }
  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ─── Date filter helper ──────────────────────────────────────────────────────

export type DateRange = {
  type: 'last30' | 'last3m' | 'last6m' | 'last1y' | 'custom';
  from?: string; // ISO date string
  to?: string;   // ISO date string
};

export function resolveDateRange(range: DateRange): { from: Date; to: Date } {
  const to = new Date();
  to.setHours(23, 59, 59, 999);
  let from = new Date();

  switch (range.type) {
    case 'last30': from.setDate(from.getDate() - 30); break;
    case 'last3m': from.setMonth(from.getMonth() - 3); break;
    case 'last6m': from.setMonth(from.getMonth() - 6); break;
    case 'last1y': from.setFullYear(from.getFullYear() - 1); break;
    case 'custom':
      from = range.from ? new Date(range.from) : from;
      return { from, to: range.to ? new Date(range.to + 'T23:59:59') : to };
  }

  from.setHours(0, 0, 0, 0);
  return { from, to };
}

/** Returns true when `dateStr` (ISO) falls within [from, to] */
export function inRange(dateStr: string | null | undefined, from: Date, to: Date): boolean {
  if (!dateStr) return false;
  const d = new Date(dateStr);
  return d >= from && d <= to;
}
